graph_dir_path: ./analysis/graphs/custom-vars-20way-1shot
logdatas:
  - 1conv-enc-on:
    label: "1 Conv, Encoder ON"
    path: ./saves/CustomNetwork/20-way-1-shot/log
  - 1conv-enc-off:
    label: "1 Conv, Encoder OFF"
    path: ./saves/CustomNetwork/20-way-1-shot-no-enc/log
  - 3conv-enc-on:
    label: "3 Conv's, Encoder ON"
    path: ./saves/CustomNetwork/20-way-1-shot-deeper/log
  - 3conv-enc-off:
    label: "3 Conv's, Encoder OFF"
    path: ./saves/CustomNetwork/20-way-1-shot-no-enc-deeper/log
